defaults:
  ipsec:
    connection:
      localIp: any
      remoteIp: any
      keyExchange: ikev2
      escCipher: aes192gcm16-aes128gcm16-ecp256,aes192-sha256-modp3072
      ikeCipher: aes192gcm16-aes128gcm16-prfsha256-ecp256-ecp521,aes192-sha256-modp3072
test: foo
vti: true
vnf_ipsec:
  path_prefix: '/tmp/'